name: 'datalake_etl-tests'
on:
  push:
    branches:
      - main
    paths:
      - '**'
  pull_request:
    branches:
      - main
    paths:
      - '**'
jobs:
  validate-sql-content:
    permissions:
      contents: read
      pull-requests: read
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq python3

      - name: Fetch changed or added files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: fetch_files
        run: |
          CHANGED_FILES=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                               -H "Accept: application/vnd.github.v3+json" \
                               https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files \
                               | jq -r '.[] | select(.status == "modified" or .status == "added") | .filename')
          
          echo "Changed or added files in this PR:"
          echo "$CHANGED_FILES"
          
          echo "$CHANGED_FILES" > changed_files.txt


      - name: Print commit details
        run: |
          echo "Pull Request Title: ${{ github.event.pull_request.title }}"
          echo "Pull Request Body: ${{ github.event.pull_request.body }}"
          echo "Head Commit Message: ${{ github.event.head_commit.message }}"
          echo "Head Commit Message (workflow_run): ${{ github.event.workflow_run.head_commit.message }}"
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"

      - name: Run Python script to check SQL files
        id: check_sql_files
        run: python3 tests/validate_sql_content_test.py changed_files.txt "${{ github.event.pull_request.title }}"
