name: 'datalake_etl-tests'
on:
  push:
    branches:
      - main
    paths:
      - '**'
  pull_request:
    branches:
      - main
    paths:
      - '**'
jobs:
  validate-sql-content:
    permissions:
      contents: read
      pull-requests: read
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch and Print PR JSON Response
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "Fetching content of PR #${PR_NUMBER}"
          
          # Fetch PR JSON data from GitHub API
          PR_JSON=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                         -H "Accept: application/vnd.github.v3+json" \
                         https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER})
          
          echo "PR JSON Response:"
          echo "$PR_JSON"
          
          # Optionally, print the PR body specifically if it's available
          echo "PR Body Content:"
          echo "$PR_JSON" | jq '.body'